# build environment
FROM node:alpine3.13 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

ARG REACT_APP_WS_URL
ENV REACT_APP_WS_URL $REACT_APP_WS_URL

COPY frontend/package.json ./
COPY frontend/package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY frontend/ ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
